services:
  - type: web
    name: backend-api
    env: node
    envVars:
      - key: VITE_API_URL
        value: http://quiz-plataform.vercel.app
      - key: URL1
        value: http://quiz-plataform.vercel.app
      - key: URL2
        value: http://quiz-plataform.vercel.app
    buildCommand: |
      cd backend && npm install
      echo "VITE_API_URL=$BACKEND_URL" > .env
      echo "URL1=$BACKEND_URL" > .env
      echo "URL2=$BACKEND_URL" > .env
      echo "VITE_API_URL=$BACKEND_URL" > .env.development
      echo "URL1=$BACKEND_URL" > .env.development
      echo "URL2=$BACKEND_URL" > .env.development
    startCommand: cd backend && node server.js
    disk:
      name: backend
      mountPath: /opt/render/project/src/backend
      sizeGB: 1
    staticPublishPath: ./backend/public
    healthCheckPath: /api/health

  - type: static
    name: frontend-app
    buildCommand: cd frontend && npm install && npm run build
    publishPath: frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

routes:
  - type: rewrite
    source: /api/*
    destination: https://backend-api.onrender.com/api/:splat
  - type: rewrite
    source: /public/*
    destination: https://backend-api.onrender.com/public/:splat