services:
  - type: web
    name: backend-api
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    disk:
      name: backend
      mountPath: /opt/render/project/src/backend
      sizeGB: 1
    healthCheckPath: /api/health
    envVars:
      - key: VITE_API_URL
        value: https://quiz-plataform-api.onrender.com
      - key: URL1
        value: https://quiz-plataform.onrender.com
      - key: URL2
        value: https://quiz-plataform.onrender.com
      - key: FRONTEND_DOMAIN
        value: https://quiz-plataform.onrender.com

  - type: web
    name: frontend-app
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://quiz-plataform-api.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
